### ISSUE TITLE
Close window behavior

### ISSUE THREAD

**Issue by ryanpitt** [suffolk-northern/main#31]
When you close any window, the whole program stops. That's poopy.

Each GUI window should only close itself when X is clicked.
 - CTC
 - MBO
 - Track Model
 - Train Model
 - Train Controller

**Comment by violasox** [comment]
You can do this by changing the line         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); to         setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE); (I tested this and it works). It's in the generated code.

**Comment by ryanpitt** [comment]
- Track model resolved in #36.
 - Train model has a fix on branch `window-close-behavior`.

I'm cool with you guys adding your window fixes to `window-close-behavior` if you like.

**Comment by ryanpitt** [comment]
Bump. @sapike @crlsvzqz5 waiting on you guys.

**Comment by ryanpitt** [comment]
Still waiting @sapike @crlsvzqz5 

Made a PR for `window-close-behavior` #55

**Comment by rogxue** [comment]
We all gucci
