### ISSUE TITLE
Track model update too slow

### ISSUE THREAD

**Issue by ryanpitt** [suffolk-northern/main#37]
Track model `update()` takes waaaayyy too long. 100% CPU on my machine.

Steps to reproduce:
 1. Run the program with a loaded database.
 2. Use computer as hand-warmer.

Comment out this line and runs OK on my machine.
https://github.com/suffolk-northern/main/blob/948c528c3b2a1a7774ca9fae2d61aeaf92a0724a/integration/Main.java#L144

Observed on my not-so-high-performance Intel Celeron Chromebook

**Comment by rogxue** [comment]
Never had that issue, but I streamlined it a bit

**Comment by ryanpitt** [comment]
Also tested on a Macbook Pro, same issue

Can't see if it's fixed in 674363d1f95b83c56711238d28ad679622ea7021 because it crashes.

**Comment by ryanpitt** [comment]
I think #41 improved this. Can somebody else try to reproduce?

**Comment by ryanpitt** [comment]
Much improved as of d58aa2f7147086b02bf2dc8bbc80419c421bd020.
