### ISSUE TITLE
Combine track_model/ and track_model_rx/ directories

### ISSUE THREAD

**Issue by ryanpitt** [suffolk-northern/main#4]
To replace @violasox's fake track stuff with @rogxue's actual stuff.

I think GlobalCoordinates belongs with your stuff too @rogxue?

**Comment by violasox** [comment]
Fine by me, @rogxue should probably handle it though and delete anything he's not using.

**Comment by rogxue** [comment]
I'm consolidating your stuff to work with mine right now. Keep it this way for now.
