### ISSUE TITLE
Track message doesn't send after DB load

### ISSUE THREAD

**Issue by ryanpitt** [suffolk-northern/main#43]
1. Start `integration.Main` with no DB loaded.
 2. Open track model UI, load a DB.
 3. Dispatch a train from the CTC.
 4. Train doesn't get message.
 5. Restart `integration.Main`, now with existing DB.
 6. Dispatch a train from the CTC.
 7. Train gets the message.

**Comment by rogxue** [comment]
I'm aware of it. It's low importance at the moment, but I'll get it to it.

**Comment by rogxue** [comment]
Fixed in PR#52
