### ISSUE TITLE
Need method to get distance along block from Global Coordinates

### ISSUE THREAD

**Issue by violasox** [suffolk-northern/main#54]
Right now there is a method to get a Global Coordinates for a given distance along a track block, but nothing that does the opposite (distance along a block given Global Coordinates). Could you make a method like this in TrackModel with inputs (String lineName, int blockID, GlobalCoordinates gc) that returns a double. Thanks!

**Comment by rogxue** [comment]
Added on track_model_ctc branch. Accurate to a couple centimeters for the most part.

**Comment by rogxue** [comment]
Fixed in PR#52
