### ISSUE TITLE
Authority to train controller is always 4300 m

### ISSUE THREAD

**Issue by carlos-vaz** [suffolk-northern/main#91]
Traced back to at least train model. When Relay's trackMessage() is probed, authority is always 4300 m even when CTC GUI's destination block is changed and train is re-dispatched. Sometimes, authority is correct, but in the next update cycle it reverts back to 4300 m.

**Comment by sapike** [comment]
I'm not seeing this. What branch and where are you dispatching to?

**Comment by ryanpitt** [comment]
When I dispatch to section Z it changes fine.
